# Generated by Django 3.0.5 on 2020-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('plan', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='プラン')),
            ],
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='お知らせ')),
                ('num', models.IntegerField(default=0, verbose_name='ナンバー')),
                ('monday', models.IntegerField(default=0, verbose_name='月曜日')),
            ],
        ),
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='日付')),
                ('month', models.CharField(default=0, max_length=10, verbose_name='年月')),
                ('plan', models.CharField(default=0, max_length=100, verbose_name='プラン')),
                ('number_of_people', models.IntegerField(blank=True, default=0, null=True, verbose_name='プランの予約人数')),
                ('booked_people', models.TextField(blank=True, default='', null=True, verbose_name='プランの予約者')),
                ('booked_people_name', models.TextField(blank=True, default='', null=True, verbose_name='プランの予約者の名前')),
                ('time', models.CharField(default='10～11', max_length=50, verbose_name='時間')),
                ('location', models.CharField(default='スタジオ', max_length=50, verbose_name='場所')),
                ('max_book', models.IntegerField(default=7, verbose_name='最大予約人数')),
                ('plan_num', models.IntegerField(default=1, verbose_name='モデルナンバー')),
            ],
        ),
        migrations.CreateModel(
            name='SettingPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='プラン名')),
                ('price', models.IntegerField(default=500, verbose_name='料金')),
                ('location', models.CharField(max_length=50, verbose_name='場所')),
                ('max_book', models.IntegerField(default=7, verbose_name='最大予約人数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('plan_num', models.IntegerField(default=1, verbose_name='モデルナンバー')),
            ],
        ),
        migrations.CreateModel(
            name='WeekdayDefaultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(default='', max_length=100, verbose_name='曜日')),
                ('plan', models.CharField(default=0, max_length=100, verbose_name='プラン')),
                ('time', models.CharField(default='', max_length=50, verbose_name='時間')),
                ('location', models.CharField(default='スタジオ', max_length=50, verbose_name='場所')),
                ('max_book', models.IntegerField(default=7, verbose_name='最大予約人数')),
                ('plan_num', models.IntegerField(default=1, verbose_name='モデルナンバー')),
            ],
        ),
    ]
