# Generated by Django 3.0.5 on 2020-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='time_of_cancel',
            field=models.IntegerField(default=0, verbose_name='キャンセル回数'),
        ),
    ]
