# Generated by Django 3.0.5 on 2020-07-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
