# Generated by Django 3.0.5 on 2020-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0002_auto_20200710_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='month',
            field=models.CharField(default=7, max_length=2, verbose_name='月'),
        ),
    ]
