# Generated by Django 3.0.5 on 2020-07-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0004_auto_20200710_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='number_of_people_1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='プラン1の予約人数'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='number_of_people_2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='プラン2の予約人数'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='plan',
            field=models.CharField(default=0, max_length=30, verbose_name='プラン1'),
        ),
    ]
