# Generated by Django 3.0.5 on 2020-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0005_auto_20200710_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='booked_people_1',
            field=models.TextField(blank=True, default='', null=True, verbose_name='プラン1の予約者'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='booked_people_2',
            field=models.TextField(blank=True, default='', null=True, verbose_name='プラン2の予約者'),
        ),
    ]
