# Generated by Django 3.0.5 on 2020-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0006_auto_20200710_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='booked_people_1',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='booked_people_2',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='number_of_people_1',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='number_of_people_2',
        ),
        migrations.RemoveField(
            model_name='planmodel',
            name='plan2',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='booked_people',
            field=models.TextField(blank=True, default='', null=True, verbose_name='プランの予約者'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='number_of_people',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='プランの予約人数'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='plan',
            field=models.CharField(default=0, max_length=30, verbose_name='プラン'),
        ),
    ]
