# Generated by Django 3.0.5 on 2020-07-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0007_auto_20200711_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planmodel',
            name='number_of_people',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='プランの予約人数'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='plan',
            field=models.CharField(default=0, max_length=100, verbose_name='プラン'),
        ),
    ]
