# Generated by Django 3.0.5 on 2020-07-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0008_auto_20200711_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='プラン名')),
                ('time', models.CharField(max_length=50, verbose_name='時間')),
                ('location', models.CharField(max_length=50, verbose_name='場所')),
                ('max_book', models.IntegerField(default=7, verbose_name='最大予約者数')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
    ]
