# Generated by Django 3.0.5 on 2020-07-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0009_settingplanmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='plan',
            field=models.CharField(default=0, max_length=100, verbose_name='プラン'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='user',
            field=models.CharField(max_length=100, verbose_name='ユーザー名'),
        ),
    ]
