# Generated by Django 3.0.5 on 2020-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0010_auto_20200717_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingplanmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='planmodel',
            name='time',
            field=models.CharField(default='10～11', max_length=50, verbose_name='時間'),
        ),
    ]
