# Generated by Django 3.0.5 on 2020-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0011_auto_20200717_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='plan_num',
            field=models.IntegerField(default=1, verbose_name='モデルナンバー'),
        ),
    ]
