# Generated by Django 3.0.5 on 2020-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0012_planmodel_plan_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingplanmodel',
            name='plan_num',
            field=models.IntegerField(default=1, verbose_name='モデルナンバー'),
        ),
    ]
