# Generated by Django 3.0.5 on 2020-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0013_settingplanmodel_plan_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingplanmodel',
            name='price',
            field=models.TextField(default=500, verbose_name='料金'),
        ),
    ]
