# Generated by Django 3.0.5 on 2020-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0014_settingplanmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingplanmodel',
            name='price',
            field=models.IntegerField(default=500, verbose_name='料金'),
        ),
    ]
