# Generated by Django 3.0.5 on 2020-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0015_auto_20200717_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingplanmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
    ]
