# Generated by Django 3.0.5 on 2020-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0017_auto_20200717_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='selected',
            field=models.IntegerField(default=0, verbose_name='選択'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='plan',
            field=models.CharField(default='', max_length=100, verbose_name='プラン'),
        ),
    ]
