# Generated by Django 3.0.5 on 2020-07-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0018_auto_20200718_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='selected',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='plan',
            field=models.CharField(default='', max_length=1000, verbose_name='プラン'),
        ),
    ]
