# Generated by Django 3.0.5 on 2020-07-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0019_auto_20200719_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='プラン'),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='month',
            field=models.CharField(default=0, max_length=10, verbose_name='年月'),
        ),
    ]
