# Generated by Django 3.0.5 on 2020-07-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0020_auto_20200720_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='location',
            field=models.CharField(default='スタジオ', max_length=50, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='settingplanmodel',
            name='max_book',
            field=models.IntegerField(default=7, verbose_name='最大予約人数'),
        ),
    ]
