# Generated by Django 3.0.5 on 2020-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0021_auto_20200724_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='booked_people_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='プランの予約者の名前'),
        ),
    ]
