# Generated by Django 3.0.5 on 2020-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0024_notemodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='max_book',
            field=models.IntegerField(default=7, verbose_name='最大予約人数'),
        ),
    ]
