# Generated by Django 3.0.5 on 2020-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0025_planmodel_max_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='monday',
            field=models.IntegerField(default=0, verbose_name='月曜日'),
        ),
    ]
