# Generated by Django 3.0.5 on 2020-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0026_notemodel_monday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekdayDefaultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(default='', max_length=100, verbose_name='曜日')),
                ('plan', models.CharField(default=0, max_length=100, verbose_name='プラン')),
                ('number_of_people', models.IntegerField(blank=True, default=0, null=True, verbose_name='プランの予約人数')),
                ('time', models.CharField(default='10～11', max_length=50, verbose_name='時間')),
                ('location', models.CharField(default='スタジオ', max_length=50, verbose_name='場所')),
                ('max_book', models.IntegerField(default=7, verbose_name='最大予約人数')),
                ('plan_num', models.IntegerField(default=1, verbose_name='モデルナンバー')),
            ],
        ),
    ]
