# Generated by Django 3.0.5 on 2020-08-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0027_weekdaydefaultmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdaydefaultmodel',
            name='number_of_people',
        ),
        migrations.AlterField(
            model_name='weekdaydefaultmodel',
            name='time',
            field=models.CharField(default='', max_length=50, verbose_name='時間'),
        ),
    ]
